### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by simonziegler** [RickStrahl/Westwind.AspNetCore.Markdown#18]
Hi Rick,

I've been using this package for a few months (great package by the way - many thanks!). And this morning after doing some general updates I have the following exception showing in the browser when I start the project:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Westwind.AspNetCore.Markdown.MarkdownPageProcessorMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I updated some nuget packages and will try to roll them back and report whether I manage to find a cause.

**Comment by simonziegler** [comment]
Update. I rolled back all edits to a released version which works in deployment and still get this error. Sorry I have no further analysis.

**Comment by hugoqribeiro** [comment]
Hi @simonziegler . I'm having this issue. How did you closed it?

**Comment by simonziegler** [comment]
Hi Hugo, I'm afraid this was a couple of years ago and I don't recall the circumstances. Sorry.
